## Ejercicio 1

In [2]:
def multiply_matrices(A, B):
    if len(A[0]) != len(B):
        raise ValueError("Número de columnas de A debe ser igual al número de filas de B")
    result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
    return result

A1 = [
    [2, -3],
    [3, -1]
]

B1 = [
    [1, 5],
    [2, 0]
]

A2 = [
    [2, -3],
    [3, -1]
]

B2 = [
    [1, 5, -4],
    [-3, 2, 0]
]

A3 = [
    [2, -3, 1],
    [4, 3, 0],
    [5, 2, -4]
]

B3 = [
    [0, 1, -2],
    [1, 0, -1],
    [2, 3, -2]
]

A4 = [
    [2, 1, 2],
    [-2, 3, 0],
    [2, -1, 3]
]

B4 = [
    [1, -2],
    [-4, 1],
    [0, 2]
]

result1 = multiply_matrices(A1, B1)
result2 = multiply_matrices(A2, B2)
result3 = multiply_matrices(A3, B3)
result4 = multiply_matrices(A4, B4)

print("Resultado de a:")
for fila in result1:
    print(fila)

print("\nResultado de b:")
for fila in result2:
    print(fila)

print("\nResultado de c:")
for fila in result3:
    print(fila)

print("\nResultado de d:")
for fila in result4:
    print(fila)


Resultado de a:
[-4, 10]
[1, 15]

Resultado de b:
[11, 4, -8]
[6, 13, -12]

Resultado de c:
[-1, 5, -3]
[3, 4, -11]
[-6, -7, -4]

Resultado de d:
[-2, 1]
[-14, 7]
[6, 1]


## Ejercicio 2

In [4]:
import numpy as np

A = np.array([
    [4, 2, 6],
    [3, 0, 7],
    [-2, -1, -3]
])

B = np.array([
    [1, 2, 0],
    [2, 1, -1],
    [3, 1, 1]
])

C = np.array([
    [1, 1, -1, 1],
    [1, 2, -4, -2],
    [2, 1, 1, 5],
    [-1, 0, -2, -4]
])

D = np.array([
    [4, 0, 0, 0],
    [6, 7, 0, 0],
    [9, 11, 1, 0],
    [5, 4, 1, 1]
])

def check_invertibility_and_inverse(matrix):
    det = np.linalg.det(matrix)
    if det != 0:
        inverse = np.linalg.inv(matrix)
        return det, inverse
    else:
        return det, None

det_A, inv_A = check_invertibility_and_inverse(A)
det_B, inv_B = check_invertibility_and_inverse(B)
det_C, inv_C = check_invertibility_and_inverse(C)
det_D, inv_D = check_invertibility_and_inverse(D)
matrices = {'A': (det_A, inv_A), 'B': (det_B, inv_B), 'C': (det_C, inv_C), 'D': (det_D, inv_D)}

for key, value in matrices.items():
    print(f"Matriz {key}:")
    if value[1] is not None:
        print(f"  Determinante: {value[0]}")
        print(f"  Inversa:\n{value[1]}\n")
    else:
        print(f"  Determinante: {value[0]}")
        print("  La matriz es singular y no tiene inversa.\n")


Matriz A:
  Determinante: 0.0
  La matriz es singular y no tiene inversa.

Matriz B:
  Determinante: -8.000000000000002
  Inversa:
[[-0.25   0.25   0.25 ]
 [ 0.625 -0.125 -0.125]
 [ 0.125 -0.625  0.375]]

Matriz C:
  Determinante: 0.0
  La matriz es singular y no tiene inversa.

Matriz D:
  Determinante: 28.00000000000001
  Inversa:
[[ 0.25        0.          0.          0.        ]
 [-0.21428571  0.14285714 -0.         -0.        ]
 [ 0.10714286 -1.57142857  1.         -0.        ]
 [-0.5         1.         -1.          1.        ]]



## Ejercicio 3

In [5]:
import numpy as np

A = np.array([
    [1, -1, 2, -1],
    [1, 0, -1, 1],
    [2, 1, 3, -4],
    [0, -1, 1, -1]
])

b1 = np.array([6, 4, -2, 5])
b2 = np.array([1, 1, 2, -1])

x1 = np.linalg.solve(A, b1)
x2 = np.linalg.solve(A, b2)

print("Solución del primer sistema (x1, x2, x3, x4):")
print(x1)

print("\nSolución del segundo sistema (x1, x2, x3, x4):")
print(x2)


Solución del primer sistema (x1, x2, x3, x4):
[ 3. -6. -2. -1.]

Solución del segundo sistema (x1, x2, x3, x4):
[1. 1. 1. 1.]


## Ejercicio 4

In [7]:
import sympy as sp

alpha = sp.symbols('alpha')

A = sp.Matrix([
    [1, -1, alpha],
    [2, 2, 1],
    [0, alpha, -3/2]
])

det_A = A.det()
alpha_solutions = sp.solve(det_A, alpha)
print("Valores de alpha que hacen que la matriz A sea singular:")
print(alpha_solutions)


Valores de alpha que hacen que la matriz A sea singular:
[-1.50000000000000, 2.00000000000000]


## Ejercicio 5

In [10]:
import numpy as np
from scipy.linalg import lu, lu_factor, lu_solve

A1 = np.array([[1, 0, 0], [2, 1, 0], [-1, 0, 1]])
B1 = np.array([[2, 3, -1], [0, -2, 1], [0, 0, 3]])
C1 = np.array([2, -1, 1])

A2 = np.array([[2, 0, 0], [-1, 1, 0], [3, 2, -1]])
B2 = np.array([[1, 1, 1], [0, 1, 2], [0, 0, 1]])
C2 = np.array([-1, 3, 0])
P1, L1, U1 = lu(A1)
B1_inv = np.linalg.inv(B1)
A1_prime = np.dot(B1_inv, A1)
lu1, piv1 = lu_factor(A1_prime)
x1 = lu_solve((lu1, piv1), C1)

P2, L2, U2 = lu(A2)
B2_inv = np.linalg.inv(B2)
A2_prime = np.dot(B2_inv, A2)
lu2, piv2 = lu_factor(A2_prime)
x2 = lu_solve((lu2, piv2), C2)
print("Solución del sistema a:")
print(x1)
print("Solución del sistema b:")
print(x2)


Solución del sistema a:
[-2.13162821e-16  3.00000000e+00  3.00000000e+00]
Solución del sistema b:
[ 1.  4. 11.]


## Ejercicio 6

In [11]:
import numpy as np
from scipy.linalg import lu

matrices = {
    'a': np.array([[2, -1, 1], [3, 3, 9], [3, 3, 5]]),
    'b': np.array([[1.012, -2.132, 3.104], [-2.132, 4.096, -7.013], [3.104, -7.013, 0.014]]),
    'c': np.array([[2, 0, 0, 0], [1, 1.5, 0, 0], [0, -3, 0.5, 0], [2, -2, 1, 1]]),
    'd': np.array([[2.1756, 4.0231, -2.1732, 5.1967], [-4.0231, 6, 0, 1.1973], [-1, -5.2107, 1.1111, 0], [6.0235, 7, 0, -4.1561]])
}
factorizaciones = {}
for key, matrix in matrices.items():
    P, L, U = lu(matrix)
    factorizaciones[key] = (L, U)
for key, (L, U) in factorizaciones.items():
    print(f"Factorización LU de la matriz {key}:")
    print("L:")
    print(L)
    print("U:")
    print(U)
    print()


Factorización LU de la matriz a:
L:
[[ 1.          0.          0.        ]
 [ 0.66666667  1.          0.        ]
 [ 1.         -0.          1.        ]]
U:
[[ 3.  3.  9.]
 [ 0. -3. -5.]
 [ 0.  0. -4.]]

Factorización LU de la matriz b:
L:
[[ 1.          0.          0.        ]
 [-0.68685567  1.          0.        ]
 [ 0.32603093 -0.21424728  1.        ]]
U:
[[ 3.104      -7.013       0.014     ]
 [ 0.         -0.72091881 -7.00338402]
 [ 0.          0.          1.59897957]]

Factorización LU de la matriz c:
L:
[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 1.          0.66666667  1.          0.        ]
 [ 0.5        -0.5         0.375       1.        ]]
U:
[[ 2.          0.          0.          0.        ]
 [ 0.         -3.          0.5         0.        ]
 [ 0.          0.          0.66666667  1.        ]
 [ 0.          0.          0.         -0.375     ]]

Factorización LU de la matriz d:
L:
[[ 1.          0.          0.     

## Ejercicio 7

In [14]:
import numpy as np

def lu_decomposition(A):
    A = A.astype(float)
    n = len(A)
    L = np.eye(n)
    U = np.copy(A)
    
    for i in range(n):
        for j in range(i + 1, n):
            factor = U[j, i] / U[i, i]
            U[j, i:] -= factor * U[i, i:]
            L[j, i] = factor
    
    return L, U

def solve_lu(L, U, b):
    y = np.zeros_like(b, dtype=np.double)
    for i in range(len(b)):
        y[i] = b[i] - np.dot(L[i, :i], y[:i])
    x = np.zeros_like(b, dtype=np.double)
    for i in range(len(b) - 1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i + 1:], x[i + 1:])) / U[i, i]
    return x

sistemas = {
    'a': (np.array([[2, -1, 1], [3, 3, 9], [3, 3, 5]]), np.array([-1, 0, 4])),
    'b': (np.array([[1.012, -2.132, 3.104], [-2.132, 4.096, -7.013], [3.104, -7.013, 0.014]]), np.array([1.984, -5.049, -3.895])),
    'c': (np.array([[2, 0, 0, 0], [1, 1.5, 0, 0], [0, -3, 0.5, 0], [2, -2, 1, 1]]), np.array([3, 4.5, -6.6, 0.8])),
    'd': (np.array([[2.1756, 4.0231, -2.1732, 5.1967], [-4.0231, 6, 0, 1.1973], [-1, -5.2107, 1.1111, 0], [6.0235, 7, 0, -4.1561]]), np.array([17.102, -6.1593, 3.0004, 0]))
}

soluciones = {}
for key, (A, b) in sistemas.items():
    L, U = lu_decomposition(A)
    x = solve_lu(L, U, b)
    soluciones[key] = x
soluciones


{'a': array([ 1.,  2., -1.]),
 'b': array([1., 1., 1.]),
 'c': array([ 1.5,  2. , -1.2,  3. ]),
 'd': array([2.9398512 , 0.0706777 , 5.67773512, 4.37981223])}